### ISSUE TITLE
UIBC doesn't work on windows 10 (laptop)

### ISSUE THREAD

**Issue by jiahaoChen** [albfan/miraclecast#139]
Hi, 
UIBC worked normal with **samsung galaxy tab s2** on wip/windows-fix, 
but, it can't work on window10 laptop(not surface4), 
The wireshark captured the package from miraclecast to windows,
![wireshark](https://lh3.googleusercontent.com/nmM1xZ6P0S5VBbYpukKJ101eioVMsn1sneH9qNTJlrdOASB2sornMLp6vm2lY4TtPeQ0q_06f2W5BOc=w1855-h966-rw)
laptop got the package, but didn't do anything.

**Comment by midi1996** [comment]
Did you check "Allow Input..." when connected? It should work. If your device is quite old (like 3rd Gen intel CPU computers or older) may not work, you need a new

**Comment by albfan** [comment]
@midi1996 this is related with this comment

**Comment by albfan** [comment]
@jiahaoChen

check if this fixes your problem:

https://github.com/albfan/miraclecast/commit/e5795edd0459ea13a409c93f8e7b0ea1e263819d

Just update repo, commit is on master

**Comment by jiahaoChen** [comment]
@albfan 
I have two issue
First, the the uibc-viewer didn't open when used tab(galaxy s2) and laptop(asus UX360C)
[e5795ed](https://github.com/albfan/miraclecast/commit/e5795edd0459ea13a409c93f8e7b0ea1e263819d)
fixed this issue.
The uibc-viewer opened, and worked on tab, 
but laptop still has problem,
so the second issue is uibc still can't work on laptop.

**Comment by albfan** [comment]
I'm little confusing. tab is an androis OS, right? and your laptop seems to have windows 10. Where is miraclecast installed in?

Did you install linux on samsung galaxy tab? I just read it seems to be possible.

Please describe what device and operative system is the source and with device operative systems is the sink, it is not obvious to me.

**Comment by albfan** [comment]
Sorry I reread all again. So this fixed samsung galaxy tab to linux but didn't solve windows to linux, right?

that's where we are on windows support. See https://github.com/albfan/miraclecast/issues/103#issuecomment-255583589. What you describe is the state of the art of the issue.

**Comment by albfan** [comment]
Let me close this issue (fix uibc for non windows devices) and remove last comments on #103 (see they only hides the state of the issue as they are unrelated?)

**Comment by jiahaoChen** [comment]
Yes, on my test result, UIBC was still not working on windows10(surface4 and laptop). 
@midi1996 can use UIBC on windows10?
Can you post the step?
I already click the check button, to allow the UIBC on laptop,
but it still not work.

**Comment by jiahaoChen** [comment]
@albfan 
I used screenBeamMini2, 
window 10 <=> screenBeamMini2
it's UIBC is worked.
so, I captured the package, it was different with miraclecast UIBC package (window10 <=> ubuntu miraclecast), 
[screenBeam](https://drive.google.com/file/d/0BzF9qALNOBNeaURoalhIZEQxXzg/view?usp=sharing)
[Miraclecast](https://drive.google.com/file/d/0BzF9qALNOBNeNFJnUTdWZFJBajA/view?usp=sharing)
Can you tell me where the UIBC keycode reference?

**Comment by albfan** [comment]
About keycode reference I didn't know I do it by reverse engineering. See #88

**Comment by jiahaoChen** [comment]
@albfan 
Sorry for bothering you again,
I still can't work UIBC between windows 10 and miracle(ubuntu16.04)
I used ScreenBeamMini2 (a WiDi display device), 
Its UIBC is worked with windows 10, 
I captured the package, 
[screenbeam_rtsp_log.txt](https://github.com/albfan/miraclecast/files/602632/screenbeam_rtsp_log.txt)
the rtsp negotiation was different between ScreenBeamMini and miraclecast
and the UIBC packages are also difference, 
Is that mean window 10(laptop) UIBC command difference with android(mobile)?
Does you have any suggestion on the issue?

**Comment by albfan** [comment]
Don't worry at al. Try pushing in this, seems miracast implementations are heterogeneous.

Let me review and find the problem. Maybe we need to capture  some more sessions to fix this

**Comment by albfan** [comment]
From this message:

    wfd_uibc_capability: input_category_list=HIDC;generic_cap_list=none;hidc_cap_list=Keyboard/USB, Mouse/USB, SingleTouch/USB, MultiTouch/USB;port=32555

Seems that UIBC is using HIDC. miraclecast has only generic UIBC implemented. 

Read section 4.11.3.2 on https://www.wi-fi.org/file/wi-fi-display-technical-specification-v11 for more details

We can confirm if you post here wireshark capture from port 32555.

I'm curious: Since ScreenBeamMini2 is a dongle for TV

https://www.youtube.com/watch?v=jstUvkfZwr8

how do you use UIBC there? with your remote control?

**Comment by jiahaoChen** [comment]
Yes, the wireshark capture from port 32555
![screenbeammini2](https://cloud.githubusercontent.com/assets/2569345/20508302/9ae173f4-b09b-11e6-960d-557c8ea36998.png)
the line duplicate to two way, one way for power, other way for USB input(or update)
https://www.youtube.com/watch?v=AuML50tE8Qk
sorry, I didn't find other video in English.

**Comment by albfan** [comment]
Upload then a capture on 32555, but can promise to implement it, if you can make progress on your own I will try to help you. Try to follow documentation

**Comment by jiahaoChen** [comment]
Ok, I will try.
Mouse press data:
00 11 00 10 01 00 00 00 07 01 01 01 00 00
Mouse release data:
00 11 00 10 01 00 00 00 07 01 01 00 00 00

**Comment by jiahaoChen** [comment]
The documentation references "Device Class Definition for Human InterfaceDevices (HID)", 
E.10 Report Descriptor (Mouse), I can't understand the table mean.
![image](https://cloud.githubusercontent.com/assets/2569345/20513039/764a7644-b0be-11e6-85ac-27a1f5999d09.png)

**Comment by jiahaoChen** [comment]
I imitated the message of screenbeammini2, 
The keyboard was worked, 
but the mouse still didn't have any reaction.

**Comment by albfan** [comment]
Please upload code changes and lets add that as HIDC implementation. That would guide us to implement HIDC for mouse

**Comment by jiahaoChen** [comment]
Do you mean I push the test code to repository?
or I paste my test code here?

**Comment by albfan** [comment]
I prefer a Pull request from your fork. A patch would be enough too:

    $ git diff origin/master > hidc_patch

Do as you will. It is not important to be polish or finished, it is just to figure out the changes needed. We can review and refactor it later

**Comment by albfan** [comment]
Although implement HIDC is interesting, in this wip (windows-fix) I use the UIBC parameters from a windows 10 machine, and commented out the old configuration

https://github.com/albfan/miraclecast/commit/87b8e1deb0e23f7ae5c81556a298b61d3d5fbcc8#diff-14da96f4f7fcebfe766ec04c303c23e2R122

Can you check if using the old configuration (i.e uncomment and comment new configuration) mouse works correctly? See there's movements and keys unmapped, but if it works we can decide whether or not this is an important implementation for windows devices.

Please check and post here your results

**Comment by jiahaoChen** [comment]
Sorry, I didn't catch.
Does you mean that I revert the 87b8e1d?
The result made the windows 10 didn't open the controlling click button.
Following is my step:
1. only revert 87b8e1d
2. sudo make install 
3. sudo miracle-wifid --log-level trace --wpa-loglevel 7
4. sudo miracle-sinkctl **--uibc** --log-level trace --log-journal-level 10

Is it the main different part?  
input_category_list=**GENERIC** vs input_category_list=**GENERIC, HIDC;**

`check_and_response_option("wfd_uibc_capability",
								      "input_category_list=GENERIC, HIDC;"
									  "generic_cap_list=Keyboard;"
									  "hidc_cap_list=Keyboard/USB, Mouse/USB, MultiTouch/USB, Gesture/USB, RemoteControl/USB;"
									  "port=none");`
- - - - - - - -  - - -- - - - - - - -  - - -- - - - - - - -  - - -- - - - - - - -  - - -- - - - - - - -  - - -- - - - - - - -  - - -
`if (rtsp_message_read(m, "{<>}", "wfd_uibc_capability") >= 0 && uibc_option) {
		char wfd_uibc_capability[512];
		sprintf(wfd_uibc_capability,
			"wfd_uibc_capability: input_category_list=GENERIC;"
         "generic_cap_list=Mouse,SingleTouch;"
         "hidc_cap_list=none;port=none");
		r = rtsp_message_append(rep, "{&}", wfd_uibc_capability);
		if (r < 0)
			return cli_vERR(r);
	}`

I have removed the HIDC, and added the screenbeammini2's message, but it still didn't work.
I will pull request my code.

**Comment by albfan** [comment]
Just uncomment/comment those lines on top of wip/windows-fix. Rest of commit is neccesary for windows.

I can provide a branch for you to test if that's easier.

**Comment by jiahaoChen** [comment]
Ok, can you provide the branch, please?
I thinks that will be more closed your mean.

**Comment by jiahaoChen** [comment]
@albfan 
Following is test result
```
now running on link 3
[ADD] Peer: 12:9f:a9:2e:f3:d1@3
[ADD] Peer: 44:85:00:54:c5:f0@3
[PROV] Peer: 44:85:00:54:c5:f0@3 Type: pbc PIN: 
[GO NEG] Peer: 44:85:00:54:c5:f0@3 Type: pbc PIN: 
[CONNECT] Peer: 44:85:00:54:c5:f0@3
now running on peer 44:85:00:54:c5:f0@3
DEBUG: connection established (sink_connected() in ctl-sink.c:404)
NOTICE: SINK connected
DEBUG: INCOMING: OPTIONS * RTSP/1.0
Require: org.wfa.wfd1.0
CSeq: 1


 (sink_handle() in ctl-sink.c:342)
DEBUG: OUTGOING: RTSP/1.0 200 OK
Public: "org.wfa.wfd1.0, GET_PARAMETER, SET_PARAMETER"
CSeq: 1


 (sink_handle_options() in ctl-sink.c:51)
DEBUG: OUTGOING: OPTIONS * RTSP/1.0
Require: org.wfa.wfd1.0
CSeq: 1


 (sink_handle_options() in ctl-sink.c:74)
DEBUG: INCOMING: RTSP/1.0 200 OK
Server: MSMiracastSource/10.00.10011.16384 guid/0D7A358B-4647-0001-0553-7A0D4746D201
Public: org.wfa.wfd1.0, SETUP, TEARDOWN, PLAY, PAUSE, GET_PARAMETER, SET_PARAMETER
CSeq: 1


 (sink_req_fn() in ctl-sink.c:30)
DEBUG: INCOMING: GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Content-Length: 681
Content-Type: text/parameters
CSeq: 2

wfd_video_formats
wfd_audio_codecs
wfd_client_rtp_ports
wfd_display_edid
wfd_connector_type
wfd_uibc_capability
wfd_content_protection
wfd_idr_request_capability
intel_friendly_name
intel_sink_manufacturer_name
intel_sink_model_name
intel_sink_version
intel_sink_device_URL
wfdx_video_formats
microsoft_latency_management_capability
microsoft_format_change_capability
microsoft_diagnostics_capability
microsoft_cursor
intel_fast_cursor
intel_usboip
intel_interactivity_mode
intel_sink_information
intel_managed_meetings
intel_lower_bandwidth
wfdx_rotation_capability
intel_source_connection_confirmation_enabled
intel_source_connection_indicator_enabled

 (sink_handle() in ctl-sink.c:342)
DEBUG: OUTGOING: RTSP/1.0 200 OK
Content-Length: 1109
Content-Type: text/parameters
CSeq: 2

wfd_content_protection: none
wfd_video_formats: 40 00 01 10 0001bdeb 051557ff 00000fff 10 0000 001f 11 0780 0438, 02 10 0001bdeb 155557ff 00000fff 10 0000 001f 11 0780 0438
wfd_audio_codecs: LPCM 00000003 00, AAC 0000000f 00, AC3 00000007 00
wfd_client_rtp_ports: RTP/AVP/UDP;unicast 1991 0 mode=play
wfd_content_protection: none
wfd_display_edid: 0001 00ffffffffffff0051f38f50010000000e100104a51d10ff2f0000a057499b2610484f000000010101010101010101010101010101011a36809c70381f403020350025a510000018000000fc00496e7465726e616c204c43440a000000fd003c3c9a9a0e00000000000000000000000000000000000000000000000000000030
wfd_connector_type: 05
microsoft_cursor: none
wfd_idr_request_capability: 1
microsoft_latency_management_capability: none
microsoft_format_change_capability: none
microsoft_diagnostics_capability: none
intel_friendly_name: miraclecast
intel_sink_manufacturer_name: GNU Linux
intel_sink_model_name: Arch linux
intel_sink_device_URL: http://github.com/albfan/miraclecast
wfd_uibc_capability: input_category_list=GENERIC;generic_cap_list=Mouse,SingleTouch;hidc_cap_list=none;port=none

 (sink_handle_get_parameter() in ctl-sink.c:134)
DEBUG: INCOMING: SET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Content-Length: 279
Content-Type: text/parameters
CSeq: 3

wfd_video_formats: 00 00 02 10 00000100 00000000 00000000 00 0000 0000 00 none none
wfd_audio_codecs: LPCM 00000002 00
wfd_presentation_URL: rtsp://192.168.173.1/wfd1.0/streamid=0 none
wfd_client_rtp_ports: RTP/AVP/UDP;unicast 1991 0 mode=play
intel_overscan_comp: x=0, y=0

 (sink_handle() in ctl-sink.c:342)
DEBUG: OUTGOING: RTSP/1.0 200 OK
CSeq: 3


 (sink_handle_set_parameter() in ctl-sink.c:229)
DEBUG: Got URL: rtsp://192.168.173.1/wfd1.0/streamid=0
 (sink_handle_set_parameter() in ctl-sink.c:248)
SINK set resolution 1920x1080
DEBUG: INCOMING: SET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Content-Length: 27
Content-Type: text/parameters
CSeq: 4

wfd_trigger_method: SETUP

 (sink_handle() in ctl-sink.c:342)
DEBUG: OUTGOING: RTSP/1.0 200 OK
CSeq: 4


 (sink_handle_set_parameter() in ctl-sink.c:229)
DEBUG: OUTGOING: SETUP rtsp://192.168.173.1/wfd1.0/streamid=0 RTSP/1.0
Transport: RTP/AVP/UDP;unicast;client_port=1991
CSeq: 2


 (sink_handle_set_parameter() in ctl-sink.c:329)
DEBUG: INCOMING: RTSP/1.0 200 OK
Transport: RTP/AVP/UDP;unicast;client_port=1991;server_port=58994;ssrc=73950895;rtcp-fb-ssrc=6d050ffb
Server: MSMiracastSource/10.00.10011.16384 guid/0D7A358B-4647-0001-0553-7A0D4746D201
Blocksize: 1450
Session: 1132117088
CSeq: 2


 (sink_setup_fn() in ctl-sink.c:153)
DEBUG: OUTGOING: PLAY rtsp://192.168.173.1/wfd1.0/streamid=0 RTSP/1.0
Session: 1132117088
CSeq: 3


 (sink_setup_fn() in ctl-sink.c:182)
DEBUG: INCOMING: RTSP/1.0 200 OK
Server: MSMiracastSource/10.00.10011.16384 guid/0D7A358B-4647-0001-0553-7A0D4746D201
Date: Mon, 28 Nov 2016 01:51:24 GMT
Session: 1132117088
CSeq: 3


 (sink_req_fn() in ctl-sink.c:30)
DEBUG: INCOMING: GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Session: 1132117088
CSeq: 5


 (sink_handle() in ctl-sink.c:342)
DEBUG: OUTGOING: RTSP/1.0 200 OK
CSeq: 5


 (sink_handle_get_parameter() in ctl-sink.c:134)

```
Laptop's GUI also didn't see the uibc control click button.
It didn't open the uibc, 
so, we can guess windows 10 can't support generic type?

**Comment by albfan** [comment]
I think so. Let's close that branch and keep working on #154

**Comment by albfan** [comment]
The conclusion is clear. Windows need HIDC
